// Blog catalog. Each post's body lives in blog-src/content/<slug>.html.
// Run `node blog-src/build-blog.mjs` after editing to regenerate pages, blog.html and sitemap.xml.

export const CATEGORIES = [
  { id: 'storm-insurance', name: 'Storm & Insurance' },
  { id: 'costs-financing', name: 'Costs & Financing' },
  { id: 'hiring-a-roofer', name: 'Hiring a Roofer' },
  { id: 'repair-maintenance', name: 'Repair & Maintenance' },
  { id: 'materials', name: 'Materials & Roof Basics' },
  { id: 'commercial', name: 'Commercial Roofing' },
  { id: 'local-guides', name: 'Houston Area Guides' },
];

const A = 'Brand_assets/';
const SEP28 = '2026-09-28';
const OCT05 = '2026-10-05';

export const POSTS = [
  // ---------- New posts ----------
  { slug: 'houston-hurricane-season-roof-checklist', date: OCT05, cat: 'storm-insurance', img: A + 'hurricane.webp',
    title: 'Houston Hurricane Season Roof Prep Checklist',
    excerpt: 'A practical, step-by-step checklist to get your roof, gutters, and paperwork ready before a Gulf storm heads toward Houston.' },
  { slug: 'how-to-spot-hail-damage-on-your-roof', date: OCT05, cat: 'storm-insurance', img: A + 'hail v2.webp',
    title: 'How to Spot Hail Damage on Your Roof',
    excerpt: 'What hail actually does to asphalt shingles, metal, and gutters, plus the safe ground-level checks you can do after a storm.' },
  { slug: 'texas-roof-insurance-claim-guide', date: OCT05, cat: 'storm-insurance', img: A + 'hail v5.webp',
    title: 'Texas Roof Insurance Claim Guide: Step by Step',
    excerpt: 'From the first photo to the final check: how a roof claim works in Texas, what the adjuster looks for, and where homeowners lose money.' },
  { slug: 'what-to-do-after-storm-damages-your-roof', date: OCT05, cat: 'storm-insurance', img: A + 'wind.webp',
    title: 'What to Do Right After a Storm Damages Your Roof',
    excerpt: 'The first 48 hours matter. Here is what to do, what not to do, and how to protect your home and your claim after storm damage.' },
  { slug: 'wind-damage-roof-signs', date: OCT05, cat: 'storm-insurance', img: A + 'wind .webp',
    title: 'Wind Damage on a Roof: 8 Signs to Look For',
    excerpt: 'Creased, lifted, and missing shingles are not always obvious from the street. Learn the telltale signs of wind damage on Houston roofs.' },
  { slug: 'acv-vs-rcv-roof-insurance', date: OCT05, cat: 'storm-insurance', img: A + 'hail v8.webp',
    title: 'ACV vs RCV Roof Coverage: What Your Policy Really Pays',
    excerpt: 'Actual cash value and replacement cost value policies can pay very different amounts for the same roof. Here is how depreciation works.' },
  { slug: 'can-a-roofer-pay-your-deductible-in-texas', date: OCT05, cat: 'storm-insurance', img: A + 'hail v4.webp',
    title: 'Can a Roofer Pay Your Insurance Deductible in Texas?',
    excerpt: 'No, and any roofer who offers to is breaking Texas law. What the law says, why it exists, and the legal ways to lower your cost.' },
  { slug: 'class-4-impact-resistant-shingles-texas', date: OCT05, cat: 'materials', img: A + 'hail v12.webp',
    title: 'Class 4 Impact-Resistant Shingles: Are They Worth It in Texas?',
    excerpt: 'What the Class 4 rating means, how impact-resistant shingles hold up to hail, and why many Texas insurers offer a premium discount.' },
  { slug: 'roof-financing-in-texas', date: OCT05, cat: 'costs-financing', img: A + 'roof 18.webp',
    title: 'Roof Financing in Texas: How Payment Plans Work',
    excerpt: 'Your options for paying for a new roof over time, what to compare between offers, and the questions to ask before you sign.' },
  { slug: 'how-to-read-a-roofing-estimate', date: OCT05, cat: 'costs-financing', img: A + 'roof 20.webp',
    title: 'How to Read a Roofing Estimate Line by Line',
    excerpt: 'Squares, waste factor, underlayment, flashing, decking allowances. A plain-English breakdown of what belongs on a roofing quote.' },
  { slug: 'hidden-costs-of-roof-replacement', date: OCT05, cat: 'costs-financing', img: A + 'roof 22.webp',
    title: '7 Hidden Costs of a Roof Replacement (and How to Avoid Surprises)',
    excerpt: 'Rotten decking, extra layers, code upgrades and more. The costs that do not show up until the old roof comes off.' },
  { slug: 'roof-ventilation-and-attic-heat-houston', date: OCT05, cat: 'repair-maintenance', img: A + 'top view.webp',
    title: 'Roof Ventilation and Attic Heat in Houston',
    excerpt: 'Why a poorly ventilated attic shortens your roof\'s life, raises your power bill, and how intake and exhaust vents should work together.' },
  { slug: 'common-causes-of-roof-leaks', date: OCT05, cat: 'repair-maintenance', img: A + 'roof 9.webp',
    title: '9 Common Causes of Roof Leaks in Houston Homes',
    excerpt: 'Most roof leaks start at a handful of predictable spots. Here is where to look and what each type of leak usually means.' },
  { slug: 'signs-you-need-a-new-roof', date: OCT05, cat: 'repair-maintenance', img: A + 'roof 7.webp',
    title: '10 Signs You Need a New Roof',
    excerpt: 'Granules in the gutters, curling shingles, daylight in the attic. The warning signs that a repair will no longer cut it.' },
  { slug: 'black-streaks-on-roof-algae', date: OCT05, cat: 'repair-maintenance', img: A + 'roof 10.webp',
    title: 'What Causes Black Streaks on a Roof, and How to Remove Them',
    excerpt: 'Those dark stains are usually algae, not dirt. What causes them in Houston\'s humidity and how to clean them without damaging shingles.' },
  { slug: 'roof-maintenance-checklist-houston', date: OCT05, cat: 'repair-maintenance', img: A + 'worker v2 .webp',
    title: 'Seasonal Roof Maintenance Checklist for Houston Homeowners',
    excerpt: 'A season-by-season list of simple checks that catch small roof problems before they turn into expensive repairs.' },
  { slug: 'gutters-and-roof-drainage-houston', date: OCT05, cat: 'repair-maintenance', img: A + 'roof 21.webp',
    title: 'Gutters and Roof Drainage: Why They Matter in Houston',
    excerpt: 'Houston gets heavy, fast rain. How gutters, downspouts, and drip edge work together to protect your roof, fascia, and foundation.' },
  { slug: 'why-skylights-leak', date: OCT05, cat: 'repair-maintenance', img: A + 'roof 23.webp',
    title: 'Why Skylights Leak and How to Fix Them',
    excerpt: 'Skylight leaks are rarely the glass. Learn where the water really gets in, and when to repair, reflash, or replace.' },
  { slug: 'trees-and-roof-damage', date: OCT05, cat: 'repair-maintenance', img: A + 'roof 24 .webp',
    title: 'Overhanging Trees and Your Roof: Risks and Fixes',
    excerpt: 'Shade is nice, but branches, leaves, and pine needles cause real roof damage. How to manage trees around your home.' },
  { slug: 'can-a-freeze-damage-your-roof-texas', date: OCT05, cat: 'storm-insurance', img: A + 'roof 25.webp',
    title: 'Can a Texas Freeze Damage Your Roof?',
    excerpt: 'Hard freezes are rare in Houston but not harmless. How ice, frozen pipes in the attic, and condensation affect roofs.' },
  { slug: 'how-long-does-a-roof-replacement-take', date: OCT05, cat: 'hiring-a-roofer', img: A + 'worker v3 .webp',
    title: 'How Long Does a Roof Replacement Take?',
    excerpt: 'Most homes are done in one to two days, but weather, permits, and materials change the timeline. Here is what to expect.' },
  { slug: 'prepare-your-home-for-roof-replacement', date: OCT05, cat: 'hiring-a-roofer', img: A + 'worker v5.webp',
    title: 'How to Prepare Your Home for Roof Replacement Day',
    excerpt: 'A simple checklist for the week before your new roof: driveway, attic, pets, wall decor, and what the crew will need.' },
  { slug: 'roof-warranty-guide', date: OCT05, cat: 'hiring-a-roofer', img: A + 'worker v6 .webp',
    title: 'Roof Warranties Explained: Manufacturer vs Workmanship',
    excerpt: 'Two very different warranties cover a new roof. What each one covers, what voids them, and what to ask before you sign.' },
  { slug: 'hoa-rules-roof-replacement-texas', date: OCT05, cat: 'hiring-a-roofer', img: A + 'roof 17 .webp',
    title: 'HOA Rules and Roof Replacement in Texas',
    excerpt: 'How to get HOA approval for a new roof, what your HOA can and cannot require in Texas, and how to avoid delays.' },
  { slug: 'metal-roofing-in-texas', date: OCT05, cat: 'materials', img: A + 'rs=w_1440,h_1440.webp',
    title: 'Metal Roofing in Texas: Pros, Cons, and Cost Factors',
    excerpt: 'Standing seam vs exposed fastener, heat, hail, noise, and lifespan. An honest look at metal roofing for Houston homes.' },
  { slug: 'synthetic-underlayment-vs-felt', date: OCT05, cat: 'materials', img: A + 'synthethhic felt .webp',
    title: 'Synthetic Underlayment vs Felt: Which Is Better?',
    excerpt: 'The layer under your shingles matters more than most people think. How synthetic and felt underlayment compare in Texas heat.' },
  { slug: 'architectural-vs-3-tab-shingles', date: OCT05, cat: 'materials', img: A + 'shingles.webp',
    title: 'Architectural vs 3-Tab Shingles: What Is the Difference?',
    excerpt: 'Wind ratings, lifespan, warranty, and curb appeal. Why most Houston homeowners now choose architectural shingles.' },
  { slug: 'energy-efficient-roofing-houston', date: OCT05, cat: 'materials', img: A + 'roof 19 .webp',
    title: 'Energy-Efficient Roofing for Houston Heat',
    excerpt: 'Reflective shingles, lighter colors, radiant barriers, and ventilation. What actually lowers attic heat and cooling costs.' },
  { slug: 'commercial-flat-roof-maintenance-texas', date: OCT05, cat: 'commercial', img: A + 'tpo-roofing.jpg',
    title: 'Commercial Flat Roof Maintenance in Texas',
    excerpt: 'A maintenance plan for flat and low-slope commercial roofs: drains, seams, penetrations, ponding water, and inspection timing.' },
  { slug: 'tpo-vs-modified-bitumen-vs-roof-coatings', date: OCT05, cat: 'commercial', img: A + 'pvc-membranes.webp',
    title: 'TPO vs Modified Bitumen vs Roof Coatings for Commercial Buildings',
    excerpt: 'How the most common commercial roofing systems compare on heat, durability, repairs, and when a coating makes sense.' },
  { slug: 'roof-replacement-sugar-land', date: OCT05, cat: 'local-guides', img: A + 'roof1.webp',
    title: 'Roof Replacement in Sugar Land: A Homeowner\'s Guide',
    excerpt: 'HOA approvals, master-planned community rules, storm exposure, and what Sugar Land homeowners should know before replacing a roof.' },
  { slug: 'roof-replacement-pearland', date: OCT05, cat: 'local-guides', img: A + 'roof2.webp',
    title: 'Roof Replacement in Pearland: What to Know',
    excerpt: 'Closer to the coast means more wind exposure. A guide to roofing materials, storm prep, and replacement in Pearland.' },
  { slug: 'roofing-in-the-woodlands', date: OCT05, cat: 'local-guides', img: A + 'roof3.webp',
    title: 'Roofing in The Woodlands: Trees, Shade, and Your Roof',
    excerpt: 'Tall pines and heavy shade are part of The Woodlands\' charm, and a real challenge for roofs. What homeowners there should watch for.' },
  { slug: 'roof-replacement-cypress-tx', date: OCT05, cat: 'local-guides', img: A + 'roof4.webp',
    title: 'Roof Replacement in Cypress, TX: A Local Guide',
    excerpt: 'Builder-grade roofs reaching the end of their life, hail exposure, and HOA rules. What Cypress homeowners should know.' },
  { slug: 'roof-replacement-spring-tx', date: OCT05, cat: 'local-guides', img: A + 'top.webp',
    title: 'Roof Replacement in Spring, TX: What Homeowners Should Know',
    excerpt: 'Aging roofs, mature trees, and storm season. A practical guide to roof repair and replacement in Spring and Klein.' },

  // ---------- Original Roofing Advice articles ----------
  { slug: 'hiring-local-roofer-vs-storm-chaser', date: SEP28, cat: 'hiring-a-roofer', img: A + 'truck.webp',
    title: 'Hiring a Local Roofer vs Storm Chaser',
    excerpt: 'After a big storm, out-of-town crews flood Houston. How to tell a storm chaser from an established local roofer.' },
  { slug: 'does-roofing-company-age-matter', date: SEP28, cat: 'hiring-a-roofer', img: A + 'worker v8 .webp',
    title: 'Does Roofing Company Age Matter?',
    excerpt: 'Years in business can signal stability, but it is not the whole story. What to weigh when comparing roofing companies.' },
  { slug: 'verify-houston-roofer-credentials', date: SEP28, cat: 'hiring-a-roofer', img: A + 'worker v9.webp',
    title: 'The Easiest Way to Verify a Houston Roofer\'s Credentials',
    excerpt: 'Insurance, certifications, reviews, and references. A quick way to check a roofer before you let them on your roof.' },
  { slug: 'how-to-choose-a-good-roofing-contractor', date: SEP28, cat: 'hiring-a-roofer', img: A + 'worker.webp',
    title: 'How to Choose a Good Roofing Contractor Near You',
    excerpt: 'The questions to ask, the red flags to avoid, and how to compare quotes from roofing contractors.' },
  { slug: 'best-roofing-companies-in-houston-ranked', date: SEP28, cat: 'local-guides', img: A + 'roof 13 .webp',
    title: 'The Best Roofing Companies in Houston Ranked',
    excerpt: 'What "best" should actually mean when you compare Houston roofing companies, and how to measure it yourself.' },
  { slug: 'best-roofing-contractors-in-katy', date: SEP28, cat: 'local-guides', img: A + 'roof 21 .webp',
    title: 'Who Are the Best Roofing Contractors in Katy?',
    excerpt: 'How Katy homeowners can evaluate roofing contractors, from local presence to warranties and reviews.' },
  { slug: 'what-is-a-mansard-roof', date: SEP28, cat: 'materials', img: A + 'roof 23 .webp',
    title: 'What Is a Mansard Roof?',
    excerpt: 'The history, look, and practical pros and cons of the mansard roof style.' },
  { slug: 'parts-of-a-roof-diagram', date: SEP28, cat: 'materials', img: A + 'roof2.webp',
    title: '21 Most Important Parts of a Roof Diagram',
    excerpt: 'From decking to drip edge, a plain-English guide to every major part of your roof.' },
  { slug: 'what-is-roof-sheathing', date: SEP28, cat: 'materials', img: A + 'roof3.webp',
    title: 'What Is Roof Sheathing?',
    excerpt: 'The structural layer under your shingles: what it is, the types used, and signs it needs replacing.' },
  { slug: 'repair-or-replace-my-roof', date: SEP28, cat: 'repair-maintenance', img: A + 'roof4.webp',
    title: 'Should I Repair or Replace My Roof?',
    excerpt: 'Age, damage extent, and cost all factor in. How to decide between a roof repair and a full replacement.' },
  { slug: 'what-do-roofers-charge-per-hour', date: SEP28, cat: 'costs-financing', img: A + 'worker v2 .webp',
    title: 'What Do Roofers Charge Per Hour in Houston?',
    excerpt: 'Why most roofing work is priced by the job or by the square, and what drives labor costs in Houston.' },
  { slug: 'popular-roof-shingle-colors', date: SEP28, cat: 'materials', img: A + 'shingles.webp',
    title: '12 Most Popular Roof Shingle Colors',
    excerpt: 'The shingle colors Houston homeowners choose most, and how color affects heat and curb appeal.' },
  { slug: 'how-to-tell-if-a-roofer-is-lying', date: SEP28, cat: 'hiring-a-roofer', img: A + 'roof1.webp',
    title: 'How to Tell If a Roofer Is Lying?',
    excerpt: 'Pressure tactics, vague quotes, and fake damage. The warning signs of a dishonest roofer.' },
  { slug: 'what-paint-goes-with-a-brown-roof', date: SEP28, cat: 'materials', img: A + 'roof 22.webp',
    title: 'What Paint Goes With a Brown Roof?',
    excerpt: 'Exterior paint colors that pair well with brown shingles, from warm neutrals to bold accents.' },
  { slug: 'how-long-does-a-roof-last-in-texas', date: SEP28, cat: 'materials', img: A + 'roof3.webp',
    title: 'How Long Does a Roof Last in Texas?',
    excerpt: 'Texas heat, hail, and humidity shorten roof life. Typical lifespans by material and how to extend yours.' },
  { slug: 'different-types-of-roofing-materials', date: SEP28, cat: 'materials', img: A + 'roof 17 .webp',
    title: 'Different Types of Roofing Materials',
    excerpt: 'Asphalt, metal, tile, and more. How common roofing materials compare for Houston homes.' },
  { slug: 'how-much-does-a-roof-cost-in-houston', date: SEP28, cat: 'costs-financing', img: A + 'top.webp',
    title: 'How Much Does a Roof Cost in Houston, Texas?',
    excerpt: 'What drives roof replacement cost in Houston, from size and pitch to materials and decking.' },
  { slug: 'roof-drip-edge-flashing-guide', date: SEP28, cat: 'materials', img: A + 'roof 20.webp',
    title: 'Roof Drip Edge Flashing Guide',
    excerpt: 'What drip edge does, why building codes require it, and what happens when it is missing.' },
];
